In [1]:
from __future__ import print_function
import torch
print(torch.__version__)

1.7.0+cu101


In [2]:
x = [12,23,34,45,56,67,78]

In [3]:
torch.is_tensor(x)

False

In [4]:
torch.is_storage(x)

False

In [5]:
y = torch.randn(1,2,3,4,5)

In [6]:
torch.is_tensor(y)

True

In [7]:
torch.is_storage(y)

False

In [8]:
torch.numel(y) #the total number of elements in the input tensor

120

In [9]:
torch.zeros(4,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
torch.numel(torch.zeros(4,4))

16

In [11]:
torch.eye(3,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [12]:
torch.eye(5,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])

In [13]:
import numpy as np
x1 = np.array(x)

In [14]:
x1

array([12, 23, 34, 45, 56, 67, 78])

In [15]:
torch.from_numpy(x1)

tensor([12, 23, 34, 45, 56, 67, 78])

In [16]:
x1

array([12, 23, 34, 45, 56, 67, 78])

In [17]:
torch.from_numpy(x1)

tensor([12, 23, 34, 45, 56, 67, 78])

In [18]:
torch.linspace(2,10,steps=25) #linear spacing

tensor([ 2.0000,  2.3333,  2.6667,  3.0000,  3.3333,  3.6667,  4.0000,  4.3333,
         4.6667,  5.0000,  5.3333,  5.6667,  6.0000,  6.3333,  6.6667,  7.0000,
         7.3333,  7.6667,  8.0000,  8.3333,  8.6667,  9.0000,  9.3333,  9.6667,
        10.0000])

In [19]:
torch.logspace(start=-10, end=10, steps=15) #logarithmic spacing

tensor([1.0000e-10, 2.6827e-09, 7.1969e-08, 1.9307e-06, 5.1795e-05, 1.3895e-03,
        3.7276e-02, 1.0000e+00, 2.6827e+01, 7.1969e+02, 1.9307e+04, 5.1795e+05,
        1.3895e+07, 3.7276e+08, 1.0000e+10])

In [20]:
#random numbers from a uniform distribution between values 0 and 1
torch.rand(10)

tensor([0.7953, 0.2036, 0.1776, 0.4704, 0.2197, 0.6589, 0.4130, 0.6079, 0.4592,
        0.6864])

In [21]:
#random values between 0 and 1 and filled with a matrix of size r=4, c=5
torch.rand(4,5)

tensor([[0.8660, 0.1776, 0.1493, 0.8221, 0.8905],
        [0.4139, 0.5677, 0.2979, 0.6176, 0.9156],
        [0.9734, 0.8620, 0.9893, 0.4049, 0.7431],
        [0.2923, 0.9626, 0.6680, 0.7954, 0.1070]])

In [22]:
#random numbers from a normal distribution, with mean=0 and standard deviation=1
torch.randn(10)

tensor([-0.5064,  1.1752, -0.8740, -0.2948,  0.3329,  0.3158,  0.0081, -0.2146,
         0.2645,  0.3751])

In [23]:
torch.randn(4,5)

tensor([[ 0.5499, -1.3084, -0.6704,  0.0555,  0.4978],
        [-0.3096,  2.7673,  0.7748, -1.1732,  0.5333],
        [ 1.5779,  0.3263, -0.3803, -0.2927, -0.0712],
        [-0.7052,  0.7908,  0.0421,  0.5545,  1.4302]])

In [24]:
#selecting values from a range, this is called random permutation
torch.randperm(10)

tensor([6, 4, 0, 3, 7, 8, 2, 9, 1, 5])

In [25]:
#usage of a range function
torch.arange(10,40,2)

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [26]:
torch.arange(10,40)

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [27]:
d = torch.randn(4,5)
d

tensor([[-0.1918,  1.6135,  0.9606,  0.8630, -0.2177],
        [ 1.3191, -0.8313, -0.2564,  1.2866, -0.6553],
        [-1.1986, -0.2085, -0.2025,  0.5068,  0.6858],
        [ 0.1435,  0.3639,  0.5893, -0.3148,  0.1889]])

In [28]:
torch.argmin(d,dim=1)

tensor([4, 1, 0, 3])

In [29]:
torch.argmax(d,dim=1)

tensor([1, 0, 4, 2])

In [30]:
#create a 2dtensor filled with values 0
torch.zeros(4,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [31]:
#create a 1dtensor filled with values 0
torch.zeros(10)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
#indexing and performing operation on the tensots
x = torch.randn(4,5)
x

tensor([[ 0.0400, -2.6917, -0.1639, -0.8902, -1.0122],
        [-0.0989, -0.7946,  1.3330,  0.4503, -0.8978],
        [ 0.2297,  0.2028, -0.2107, -0.6108, -0.4982],
        [ 0.5610, -0.6072,  1.9183, -0.3056,  1.1050]])

In [33]:
#concatenate two tensors
torch.cat((x,x))

tensor([[ 0.0400, -2.6917, -0.1639, -0.8902, -1.0122],
        [-0.0989, -0.7946,  1.3330,  0.4503, -0.8978],
        [ 0.2297,  0.2028, -0.2107, -0.6108, -0.4982],
        [ 0.5610, -0.6072,  1.9183, -0.3056,  1.1050],
        [ 0.0400, -2.6917, -0.1639, -0.8902, -1.0122],
        [-0.0989, -0.7946,  1.3330,  0.4503, -0.8978],
        [ 0.2297,  0.2028, -0.2107, -0.6108, -0.4982],
        [ 0.5610, -0.6072,  1.9183, -0.3056,  1.1050]])

In [34]:
#concatenate n times based on array size over column
torch.cat((x,x,x),1)

tensor([[ 0.0400, -2.6917, -0.1639, -0.8902, -1.0122,  0.0400, -2.6917, -0.1639,
         -0.8902, -1.0122,  0.0400, -2.6917, -0.1639, -0.8902, -1.0122],
        [-0.0989, -0.7946,  1.3330,  0.4503, -0.8978, -0.0989, -0.7946,  1.3330,
          0.4503, -0.8978, -0.0989, -0.7946,  1.3330,  0.4503, -0.8978],
        [ 0.2297,  0.2028, -0.2107, -0.6108, -0.4982,  0.2297,  0.2028, -0.2107,
         -0.6108, -0.4982,  0.2297,  0.2028, -0.2107, -0.6108, -0.4982],
        [ 0.5610, -0.6072,  1.9183, -0.3056,  1.1050,  0.5610, -0.6072,  1.9183,
         -0.3056,  1.1050,  0.5610, -0.6072,  1.9183, -0.3056,  1.1050]])

In [35]:
#concatenate n times based on array size over row
torch.cat((x,x,x),0)

tensor([[ 0.0400, -2.6917, -0.1639, -0.8902, -1.0122],
        [-0.0989, -0.7946,  1.3330,  0.4503, -0.8978],
        [ 0.2297,  0.2028, -0.2107, -0.6108, -0.4982],
        [ 0.5610, -0.6072,  1.9183, -0.3056,  1.1050],
        [ 0.0400, -2.6917, -0.1639, -0.8902, -1.0122],
        [-0.0989, -0.7946,  1.3330,  0.4503, -0.8978],
        [ 0.2297,  0.2028, -0.2107, -0.6108, -0.4982],
        [ 0.5610, -0.6072,  1.9183, -0.3056,  1.1050],
        [ 0.0400, -2.6917, -0.1639, -0.8902, -1.0122],
        [-0.0989, -0.7946,  1.3330,  0.4503, -0.8978],
        [ 0.2297,  0.2028, -0.2107, -0.6108, -0.4982],
        [ 0.5610, -0.6072,  1.9183, -0.3056,  1.1050]])

In [36]:
a = torch.randn(4,4)
a

tensor([[-1.3936, -0.3666, -0.8261, -1.5785],
        [ 0.1440,  1.2895, -0.6238, -0.7619],
        [-0.2672, -0.9628, -0.5209,  2.3614],
        [-1.7636, -0.2729, -1.1446,  0.5847]])

In [37]:
torch.chunk(a,2)

(tensor([[-1.3936, -0.3666, -0.8261, -1.5785],
         [ 0.1440,  1.2895, -0.6238, -0.7619]]),
 tensor([[-0.2672, -0.9628, -0.5209,  2.3614],
         [-1.7636, -0.2729, -1.1446,  0.5847]]))

In [38]:
torch.chunk(a,2,0)

(tensor([[-1.3936, -0.3666, -0.8261, -1.5785],
         [ 0.1440,  1.2895, -0.6238, -0.7619]]),
 tensor([[-0.2672, -0.9628, -0.5209,  2.3614],
         [-1.7636, -0.2729, -1.1446,  0.5847]]))

In [39]:
torch.chunk(a,2,1)

(tensor([[-1.3936, -0.3666],
         [ 0.1440,  1.2895],
         [-0.2672, -0.9628],
         [-1.7636, -0.2729]]), tensor([[-0.8261, -1.5785],
         [-0.6238, -0.7619],
         [-0.5209,  2.3614],
         [-1.1446,  0.5847]]))

In [40]:
torch.Tensor([[11,12],[23,24]])

tensor([[11., 12.],
        [23., 24.]])

In [41]:
torch.gather(torch.Tensor([[11,12],[23,24]]),1,
             torch.LongTensor([[0,0],[1,0]]))

tensor([[11., 11.],
        [24., 23.]])

In [42]:
torch.LongTensor([[0,0],[1,0]])
#the 1D tensor containing the indices to index

tensor([[0, 0],
        [1, 0]])

In [43]:
a = torch.randn(4,4)
a

tensor([[-0.8101,  0.5741,  1.1950, -2.0509],
        [-1.7355, -0.4397,  0.2785, -0.2125],
        [ 1.0294, -0.2171, -1.0210,  0.8636],
        [ 0.6111, -1.4649, -0.5750, -0.1652]])

In [44]:
indices = torch.LongTensor([0,2])

In [45]:
torch.index_select(a,0, indices)

tensor([[-0.8101,  0.5741,  1.1950, -2.0509],
        [ 1.0294, -0.2171, -1.0210,  0.8636]])

In [46]:
torch.index_select(a,1, indices)

tensor([[-0.8101,  1.1950],
        [-1.7355,  0.2785],
        [ 1.0294, -1.0210],
        [ 0.6111, -0.5750]])

In [47]:
#identify null input tensors using nonzero function
torch.nonzero(torch.tensor([10,00,23,0,0.0]))

tensor([[0],
        [2]])

In [48]:
#splitting the tensor into small chunks
torch.split(torch.tensor([12,21,34,32,45,54,56,65]),2)

(tensor([12, 21]), tensor([34, 32]), tensor([45, 54]), tensor([56, 65]))

In [49]:
#splitting the tensor into small chunks
torch.split(torch.tensor([12,21,34,32,45,54,56,65]),3)

(tensor([12, 21, 34]), tensor([32, 45, 54]), tensor([56, 65]))

In [50]:
#how to reshape the tensors along a new dimension
x

tensor([[ 0.0400, -2.6917, -0.1639, -0.8902, -1.0122],
        [-0.0989, -0.7946,  1.3330,  0.4503, -0.8978],
        [ 0.2297,  0.2028, -0.2107, -0.6108, -0.4982],
        [ 0.5610, -0.6072,  1.9183, -0.3056,  1.1050]])

In [51]:
x.t() #transpose is one option to change the shape of the tensor

tensor([[ 0.0400, -0.0989,  0.2297,  0.5610],
        [-2.6917, -0.7946,  0.2028, -0.6072],
        [-0.1639,  1.3330, -0.2107,  1.9183],
        [-0.8902,  0.4503, -0.6108, -0.3056],
        [-1.0122, -0.8978, -0.4982,  1.1050]])

In [52]:
x.transpose(1,0)

tensor([[ 0.0400, -0.0989,  0.2297,  0.5610],
        [-2.6917, -0.7946,  0.2028, -0.6072],
        [-0.1639,  1.3330, -0.2107,  1.9183],
        [-0.8902,  0.4503, -0.6108, -0.3056],
        [-1.0122, -0.8978, -0.4982,  1.1050]])

In [53]:
x

tensor([[ 0.0400, -2.6917, -0.1639, -0.8902, -1.0122],
        [-0.0989, -0.7946,  1.3330,  0.4503, -0.8978],
        [ 0.2297,  0.2028, -0.2107, -0.6108, -0.4982],
        [ 0.5610, -0.6072,  1.9183, -0.3056,  1.1050]])

In [54]:
torch.unbind(x,1) #dim=1 removing a column

(tensor([ 0.0400, -0.0989,  0.2297,  0.5610]),
 tensor([-2.6917, -0.7946,  0.2028, -0.6072]),
 tensor([-0.1639,  1.3330, -0.2107,  1.9183]),
 tensor([-0.8902,  0.4503, -0.6108, -0.3056]),
 tensor([-1.0122, -0.8978, -0.4982,  1.1050]))

In [55]:
torch.unbind(x,0) #dim=0 removing a row

(tensor([ 0.0400, -2.6917, -0.1639, -0.8902, -1.0122]),
 tensor([-0.0989, -0.7946,  1.3330,  0.4503, -0.8978]),
 tensor([ 0.2297,  0.2028, -0.2107, -0.6108, -0.4982]),
 tensor([ 0.5610, -0.6072,  1.9183, -0.3056,  1.1050]))

In [56]:
x

tensor([[ 0.0400, -2.6917, -0.1639, -0.8902, -1.0122],
        [-0.0989, -0.7946,  1.3330,  0.4503, -0.8978],
        [ 0.2297,  0.2028, -0.2107, -0.6108, -0.4982],
        [ 0.5610, -0.6072,  1.9183, -0.3056,  1.1050]])

In [57]:
#adding value to the existing tensor, scalar addition
torch.add(x,20)

tensor([[20.0400, 17.3083, 19.8361, 19.1098, 18.9878],
        [19.9011, 19.2054, 21.3330, 20.4503, 19.1022],
        [20.2297, 20.2028, 19.7893, 19.3892, 19.5018],
        [20.5610, 19.3928, 21.9183, 19.6944, 21.1050]])

In [58]:
x

tensor([[ 0.0400, -2.6917, -0.1639, -0.8902, -1.0122],
        [-0.0989, -0.7946,  1.3330,  0.4503, -0.8978],
        [ 0.2297,  0.2028, -0.2107, -0.6108, -0.4982],
        [ 0.5610, -0.6072,  1.9183, -0.3056,  1.1050]])

In [59]:
#scalar multiplication
torch.mul(x,2)

tensor([[ 0.0799, -5.3834, -0.3279, -1.7804, -2.0245],
        [-0.1978, -1.5892,  2.6659,  0.9007, -1.7956],
        [ 0.4594,  0.4055, -0.4215, -1.2217, -0.9964],
        [ 1.1220, -1.2144,  3.8367, -0.6111,  2.2100]])

In [60]:
x

tensor([[ 0.0400, -2.6917, -0.1639, -0.8902, -1.0122],
        [-0.0989, -0.7946,  1.3330,  0.4503, -0.8978],
        [ 0.2297,  0.2028, -0.2107, -0.6108, -0.4982],
        [ 0.5610, -0.6072,  1.9183, -0.3056,  1.1050]])

In [61]:
intercept = torch.randn(1)
intercept

tensor([1.2046])

In [62]:
x = torch.randn(2,2)
x

tensor([[-0.3400, -0.2002],
        [-0.5198, -2.0800]])

In [63]:
beta = 0.7456
beta

0.7456

In [64]:
torch.mul(intercept,x)

tensor([[-0.4095, -0.2412],
        [-0.6261, -2.5056]])

In [65]:
torch.mul(x,beta)

tensor([[-0.2535, -0.1493],
        [-0.3875, -1.5509]])

In [66]:
#y = intercept + (beta*x)
torch.add(torch.mul(intercept,x), torch.mul(x,beta)) #tensor y

tensor([[-0.6630, -0.3905],
        [-1.0137, -4.0564]])

In [67]:
#rounding up tensor values
torch.manual_seed(1234)
torch.randn(5,5)

tensor([[-0.1117, -0.4966,  0.1631, -0.8817,  0.0539],
        [ 0.6684, -0.0597, -0.4675, -0.2153, -0.7141],
        [-1.0831, -0.5547,  0.9717, -0.5150,  1.4255],
        [ 0.7987, -1.4949,  1.4778, -0.1696, -0.9919],
        [-1.4569,  0.2563, -0.4030,  0.4195,  0.9380]])

In [68]:
torch.manual_seed(1234)
torch.ceil(torch.randn(5,5))

tensor([[-0., -0.,  1., -0.,  1.],
        [ 1., -0., -0., -0., -0.],
        [-1., -0.,  1., -0.,  2.],
        [ 1., -1.,  2., -0., -0.],
        [-1.,  1., -0.,  1.,  1.]])

In [69]:
torch.manual_seed(1234)
torch.floor(torch.randn(5,5))

tensor([[-1., -1.,  0., -1.,  0.],
        [ 0., -1., -1., -1., -1.],
        [-2., -1.,  0., -1.,  1.],
        [ 0., -2.,  1., -1., -1.],
        [-2.,  0., -1.,  0.,  0.]])

In [70]:
#truncate the values in a range say 0,1
torch.manual_seed(1234)
torch.clamp(torch.floor(torch.randn(5,5)), min=-0.3, max=0.4)

tensor([[-0.3000, -0.3000,  0.0000, -0.3000,  0.0000],
        [ 0.0000, -0.3000, -0.3000, -0.3000, -0.3000],
        [-0.3000, -0.3000,  0.0000, -0.3000,  0.4000],
        [ 0.0000, -0.3000,  0.4000, -0.3000, -0.3000],
        [-0.3000,  0.0000, -0.3000,  0.0000,  0.0000]])

In [71]:
#truncate with only lower limit
torch.manual_seed(1234)
torch.clamp(torch.floor(torch.randn(5,5)), min=-0.3)

tensor([[-0.3000, -0.3000,  0.0000, -0.3000,  0.0000],
        [ 0.0000, -0.3000, -0.3000, -0.3000, -0.3000],
        [-0.3000, -0.3000,  0.0000, -0.3000,  1.0000],
        [ 0.0000, -0.3000,  1.0000, -0.3000, -0.3000],
        [-0.3000,  0.0000, -0.3000,  0.0000,  0.0000]])

In [72]:
#truncate with only upper limit
torch.manual_seed(1234)
torch.clamp(torch.floor(torch.randn(5,5)), max=0.3)

tensor([[-1.0000, -1.0000,  0.0000, -1.0000,  0.0000],
        [ 0.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-2.0000, -1.0000,  0.0000, -1.0000,  0.3000],
        [ 0.0000, -2.0000,  0.3000, -1.0000, -1.0000],
        [-2.0000,  0.0000, -1.0000,  0.0000,  0.0000]])

In [73]:
#compute the exponential
torch.exp(x)

tensor([[0.7118, 0.8185],
        [0.5947, 0.1249]])

In [74]:
np.exp(x)

tensor([[0.7118, 0.8185],
        [0.5947, 0.1249]])

In [75]:
torch.add(x,10)

tensor([[9.6600, 9.7998],
        [9.4802, 7.9200]])

In [76]:
#getting the fractional portion of each tensor
torch.frac(torch.add(x,10))

tensor([[0.6600, 0.7998],
        [0.4802, 0.9200]])

In [77]:
#compute the log of the values in a tensor
x

tensor([[-0.3400, -0.2002],
        [-0.5198, -2.0800]])

In [78]:
torch.log(x) #log of negatives are nan

tensor([[nan, nan],
        [nan, nan]])

In [79]:
#to rectify the negative values do a power transformation
torch.pow(x,2)

tensor([[0.1156, 0.0401],
        [0.2702, 4.3265]])

In [80]:
x

tensor([[-0.3400, -0.2002],
        [-0.5198, -2.0800]])

In [81]:
#compute the sigmoid of the input tensor
torch.sigmoid(x)

tensor([[0.4158, 0.4501],
        [0.3729, 0.1111]])

In [82]:
#finding the square root of the values
x

tensor([[-0.3400, -0.2002],
        [-0.5198, -2.0800]])

In [83]:
torch.sqrt(x)

tensor([[nan, nan],
        [nan, nan]])