In [1]:
#Layers : Fundamental blocks of Neural Network
import torch
from torch.nn import Linear, ReLU
import torch.nn as nn
import numpy as np
from torch.autograd import Variable

In [2]:
myLayer = Linear(in_features=10, out_features=5, bias=True)
inp = Variable(torch.randn(1,10))
myLayer = Linear(in_features=10, out_features=5, bias=True)
myLayer(inp)

tensor([[-0.5110, -0.6567, -0.7577, -0.6810, -0.7615]],
       grad_fn=<AddmmBackward>)

In [3]:
myLayer.weight

Parameter containing:
tensor([[-0.2691, -0.1108,  0.0096, -0.1537,  0.0539, -0.3024, -0.2335, -0.2521,
          0.1516,  0.1294],
        [-0.0597, -0.1476,  0.2644, -0.0724, -0.2074, -0.2400,  0.0589, -0.2135,
          0.2398,  0.0371],
        [-0.1165,  0.2973,  0.1117,  0.2851, -0.0919, -0.2946, -0.0039,  0.0359,
          0.0583,  0.3125],
        [ 0.2225,  0.2925, -0.2816,  0.0136,  0.2813,  0.0424,  0.2677, -0.2849,
          0.0388,  0.1462],
        [ 0.1717, -0.1361,  0.2523, -0.1449,  0.2010, -0.1302, -0.1825, -0.2348,
         -0.3094, -0.2001]], requires_grad=True)

In [4]:
myLayer.bias

Parameter containing:
tensor([ 0.2584, -0.1258, -0.1378, -0.0786,  0.2008], requires_grad=True)

In [5]:
#Stacking Linear Layers
myLayer1 = Linear(10,5)
myLayer2 = Linear(5,2)
myLayer2(myLayer1(inp))

tensor([[0.4901, 0.0492]], grad_fn=<AddmmBackward>)

In [6]:
#Pytorch non-linear activations
sample_data = Variable(torch.Tensor([[1,2,-1,-1]]))
myReLU = ReLU()
myReLU(sample_data)

tensor([[1., 2., 0., 0.]])

In [7]:
#Simpler method
import torch.nn.functional as F
sample_data = Variable(torch.Tensor([[1,2,-1,-1]]))
f = F.relu(sample_data)
f

tensor([[1., 2., 0., 0.]])

In [8]:
#Neural Network
class MyFirstNetwork(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(MyFirstNetWork,self).__init__()
        self.layer1 = nn.Linear(input_size, hidden_size)
        self.layer2 = nn.Linear(hidden_size, output_size)
    
    def __forward__(self, input):
        out = self.layer1(input)
        out = nn.ReLU(out)
        out = self.layer2(out)
        return out

In [9]:
#Loss
loss = nn.MSELoss()
input = Variable(torch.randn(3,5), requires_grad=True)
target = Variable(torch.randn(3,5))
output = loss(input, target)
output.backward()

In [10]:
def cross_entropy(true_label, prediction):
    if true_label == 1:
        return -log(prediction)
    else:
        retunr -log(1 - prediction)

In [11]:
loss = nn.CrossEntropyLoss()
input = Variable(torch.randn(3,5),requires_grad=True)
target = Variable(torch.LongTensor(3).random_(5))
output = loss(input, target)
output.backward()

In [12]:
#Optimizer
'''
import torch.optim as optim
optimizer = optim.SGD(model.parameters(), lr=0.01)
for input, target in dataset:
    optimizer.zero_grad()
    output = model(input)
    loss = loss_fn(output, target)
    loss.backward()
    optimizer.step()
'''


'\nimport torch.optim as optim\noptimizer = optim.SGD(model.parameters(), lr=0.01)\nfor input, target in dataset:\n    optimizer.zero_grad()\n    output = model(input)\n    loss = loss_fn(output, target)\n    loss.backward()\n    optimizer.step()\n'